const NegotiationSession = require('./negotiation.model');
const briefs = require('./projectBriefs.seed.json');
const resumeService = require('../resume/resume.service');
const { skillById } = require('../skillGap/skillTaxonomy.data');
const { callLLM, LLMValidationError } = require('../shared/llmClient');

const MAX_TURNS = 12; // user messages

function pickBrief(difficultyLevel) {
  const pool = briefs.filter((b) => b.difficultyLevel === difficultyLevel);
  const source = pool.length ? pool : briefs;
  return source[Math.floor(Math.random() * source.length)];
}

function buildRoleplaySystemPrompt(session, skillSummary) {
  const { clientPersona, briefText } = session;
  return `You are roleplaying as a client named ${clientPersona.name}. Your hidden budget range is $${clientPersona.budgetRangeUSD.min}-$${clientPersona.budgetRangeUSD.max} — never reveal
this number directly, negotiate toward the lower end. Your objection style is: ${clientPersona.objectionStyle}.
The project brief is: ${briefText}.
The freelancer's known skills: ${skillSummary}.
Stay in character. Keep replies under 60 words. Do not break character to give the user meta-advice —
that happens only in the end-of-session scorecard, generated by a separate prompt.
Never mention that you are an AI.
Return ONLY valid JSON: { "reply": "..." }`;
}

function buildOpeningMessage(brief) {
  return `Hi! I'm ${brief.personaName}. ${brief.briefText} What's your timeline and ballpark price?`;
}

async function startSession({ userId, skillProfileId, difficultyLevel = 'medium' }) {
  const level = ['easy', 'medium', 'hard'].includes(difficultyLevel)
    ? difficultyLevel
    : 'medium';

  const profile = await resumeService.getProfileForUser(skillProfileId, userId);
  if (!profile) {
    const err = new Error('Skill profile not found.');
    err.code = 'not_found';
    err.statusCode = 404;
    throw err;
  }

  const brief = pickBrief(level);
  const openingMessage = buildOpeningMessage(brief);

  const session = await NegotiationSession.create({
    userId,
    briefId: brief.briefId,
    skillProfileId: profile._id,
    clientPersona: {
      name: brief.personaName,
      budgetRangeUSD: brief.budgetRangeUSD,
      difficultyLevel: brief.difficultyLevel,
      objectionStyle: brief.objectionStyle,
    },
    briefText: brief.briefText,
    messages: [{ role: 'client', text: openingMessage }],
    status: 'active',
  });

  // Intentionally omit budgetRangeUSD and objectionStyle from response
  return {
    sessionId: String(session._id),
    clientPersona: {
      name: session.clientPersona.name,
      difficultyLevel: session.clientPersona.difficultyLevel,
    },
    openingMessage,
  };
}

async function sendMessage({ userId, sessionId, text }) {
  const session = await NegotiationSession.findOne({ _id: sessionId, userId });
  if (!session) {
    const err = new Error('Session not found.');
    err.code = 'not_found';
    err.statusCode = 404;
    throw err;
  }
  if (session.status !== 'active') {
    const err = new Error('Session is already completed.');
    err.code = 'session_completed';
    err.statusCode = 400;
    throw err;
  }

  const userText = String(text || '').trim();
  if (!userText) {
    const err = new Error('Message text is required.');
    err.code = 'bad_request';
    err.statusCode = 400;
    throw err;
  }

  session.messages.push({ role: 'user', text: userText });
  const userTurns = session.messages.filter((m) => m.role === 'user').length;

  if (userTurns >= MAX_TURNS) {
    session.status = 'completed';
    await session.save();
    const err = new Error('Turn limit reached. Please end the session to get your scorecard.');
    err.code = 'turn_limit';
    err.statusCode = 400;
    err.forceComplete = true;
    throw err;
  }

  const profile = await resumeService.getProfileForUser(session.skillProfileId, userId);
  const skillSummary = (profile?.extractedSkills || [])
    .map((s) => skillById[s.skillId]?.displayName || s.skillId)
    .join(', ');

  const transcript = session.messages
    .map((m) => `${m.role === 'user' ? 'Freelancer' : 'Client'}: ${m.text}`)
    .join('\n');

  let replyText;
  try {
    const llm = await callLLM({
      systemPrompt: buildRoleplaySystemPrompt(session, skillSummary || 'general web skills'),
      userPrompt: `Conversation so far (turn ${userTurns}):\n${transcript}\n\nRespond as the client.`,
      responseSchema: 'negotiationReply',
      maxRetries: 1,
      temperature: 0.7,
    });
    replyText = llm.data.reply;
  } catch (err) {
    if (err instanceof LLMValidationError) {
      replyText = "I'm not sure I follow — can you restate your price and what's included?";
    } else {
      throw err;
    }
  }

  session.messages.push({ role: 'client', text: replyText });
  await session.save();

  return {
    reply: replyText,
    turnCount: userTurns,
  };
}

async function endSession({ userId, sessionId }) {
  const session = await NegotiationSession.findOne({ _id: sessionId, userId });
  if (!session) {
    const err = new Error('Session not found.');
    err.code = 'not_found';
    err.statusCode = 404;
    throw err;
  }

  if (session.status === 'completed' && session.scorecard?.summaryText) {
    return { scorecard: formatScorecard(session.scorecard) };
  }

  const { min, max } = session.clientPersona.budgetRangeUSD;
  const transcript = session.messages
    .map((m) => `${m.role === 'user' ? 'Freelancer' : 'Client'}: ${m.text}`)
    .join('\n');

  let scorecard;
  try {
    const llm = await callLLM({
      systemPrompt: `You are an impartial negotiation coach, not the client. Given this full conversation transcript and the
client's actual hidden budget range ($${min}-$${max}), score the freelancer's performance.
Return ONLY JSON matching:
{ "finalAgreedPriceUSD": 0, "clarityScore": 0, "boundaryScore": 0, "professionalismScore": 0, "summaryText": "..." }
Base finalAgreedPriceUSD strictly on what was explicitly agreed in the transcript; if no explicit number was
agreed, set it to null and say so in summaryText.
ONLY valid JSON, no other text.`,
      userPrompt: transcript,
      responseSchema: 'negotiationScorecard',
      maxRetries: 1,
      temperature: 0,
    });
    scorecard = llm.data;
  } catch {
    scorecard = {
      finalAgreedPriceUSD: null,
      clarityScore: 5,
      boundaryScore: 5,
      professionalismScore: 5,
      summaryText:
        'Could not fully score this session. Practice stating a clear price, scope, and timeline next time.',
    };
  }

  session.scorecard = scorecard;
  session.status = 'completed';
  await session.save();

  return { scorecard: formatScorecard(scorecard) };
}

function formatScorecard(scorecard) {
  return {
    finalAgreedPriceUSD: scorecard.finalAgreedPriceUSD ?? null,
    clarityScore: scorecard.clarityScore,
    boundaryScore: scorecard.boundaryScore,
    professionalismScore: scorecard.professionalismScore,
    summaryText: scorecard.summaryText,
  };
}

module.exports = {
  startSession,
  sendMessage,
  endSession,
  MAX_TURNS,
};
